### ISSUE TITLE
FriendFeed is shutting down

### ISSUE THREAD

**Issue by miyagawa** [punytan/cpan_new#6]
http://weblog.bulknews.net/post/113186012659/friendfeed-is-shutting-down

The script should be updated to fetch the updates from MetaCPAN directly, i think.

**Comment by punytan** [comment]
Thank you for summing up the current status.
I'll rewrite the subscriber parts to pull from /recent page of metacpan.

**Comment by punytan** [comment]
See also: thread on twitter https://twitter.com/miyagawa/status/575017735500910593
