### ISSUE TITLE
Change links from http to https

### ISSUE THREAD

**Issue by bessarabov** [punytan/cpan_new#7]
JFYI.

Now your twitter account is uses http links to metacpan. I've created issue https://github.com/CPAN-API/metacpan-web/issues/1488 for metacpan to change the scheme. When that ticket will be solved you will automatically post https links.

**Comment by punytan** [comment]
cool

**Comment by bessarabov** [comment]
Metacpan has released new version. Now https://metacpan.org/feed/recent return https links, and all the tweets at https://twitter.com/cpan_new automaticly got https links.

So this issues is soleved, I'm closing it.

**Comment by punytan** [comment]
thank you!
