### ISSUE TITLE
Distros with long name potentially cause an infinite loop

### ISSUE THREAD

**Issue by zoffixznet** [punytan/cpan_new#8]
Releases whose names are long enough to cause the tweet to be more than 140 chars long (e.g. [this one](https://metacpan.org/release/ZOFFIX/Acme-Net-FullAuto-0.9999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999)) potentially cause an infinite loop of trying to announce the dist.

The `$item->{title}` [here](https://github.com/punytan/cpan_new/blob/50f6e6edfdb1b25a3d1a3cd285d172991bf1039a/script/cpan_new.pl#L40) should likely be abridged if the total length of the tweet exceeds 140 chars (I can submit a PR, if you'd like).

Glancing at the code, what concerned me is [this line](https://github.com/punytan/cpan_new/blob/50f6e6edfdb1b25a3d1a3cd285d172991bf1039a/script/cpan_new.pl#L61). I did not dig deep enough to find out whether that's the path that would be taken in the case of exceeding 140 char limit. If it is, then the bot would try to reannounce the tweet infinitely.

**Comment by punytan** [comment]
It is just as you wrote it. The problem occurred and I found an evidence in logs. So I will fix this problem soon.
Thank you very much for reporting the issue!

**Comment by punytan** [comment]
Fixed script has been deployed :)

**Comment by zoffixznet** [comment]
\o/ Awesome!
